(package! atomic-chrome)
(package! ob-mermaid)
(package! mermaid-mode)
(package! ox-reveal)
(package! deadgrep)
(package! elixir-ts-mode)
(package! lsp-tailwindcss :recipe (:host github :repo "merrickluo/lsp-tailwindcss"))
