# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  anime4k = {
    pname = "anime4k";
    version = "8e39551ce96ed172605c89b7dd8be855b5502cc9";
    src = fetchFromGitHub {
      owner = "bloc97";
      repo = "Anime4K";
      rev = "8e39551ce96ed172605c89b7dd8be855b5502cc9";
      fetchSubmodules = false;
      sha256 = "sha256-01js/vr+kpFAm2Hfj64ad+odZKYiC9TZiTTj6mwAFd8=";
    };
    date = "2023-05-26";
  };
  khinsider = {
    pname = "khinsider";
    version = "b1683fbf2897f04242bd8e67eade940d1b6f2f16";
    src = fetchFromGitHub {
      owner = "obskyr";
      repo = "khinsider";
      rev = "b1683fbf2897f04242bd8e67eade940d1b6f2f16";
      fetchSubmodules = false;
      sha256 = "sha256-sSxLicoqS41Ofw5M0K3ERbYZAYe4lgQPKpzWdHNl0vA=";
    };
    date = "2022-05-09";
  };
}
