# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  anime4k = {
    pname = "anime4k";
    version = "7684e9586f8dcc738af08a1cdceb024cc184f426";
    src = fetchFromGitHub {
      owner = "bloc97";
      repo = "Anime4K";
      rev = "7684e9586f8dcc738af08a1cdceb024cc184f426";
      fetchSubmodules = false;
      sha256 = "sha256-F5/n/KmJ7iOiI0qcpwX6q8zvF4ACv6zcJTOxcAv6HSE=";
    };
    date = "2024-04-25";
  };
  khinsider = {
    pname = "khinsider";
    version = "cc1bdc1807fba5d282fe8c6e3cfc10141c26865d";
    src = fetchFromGitHub {
      owner = "kerunaru";
      repo = "khinsider";
      rev = "cc1bdc1807fba5d282fe8c6e3cfc10141c26865d";
      fetchSubmodules = false;
      sha256 = "sha256-3BliQzSEkPw4bjXvTq/xkGr6we6BCKV75ZCC11oS5MY=";
    };
    date = "2025-06-28";
  };
}
